version: '3.8'

services:

  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python app.py 0.0.0.0:5000
    depends_on:
      - db

  bot:
    build: .
    restart: always
    command: python modules/bot.py
    depends_on:
      - db

  db:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
